### ISSUE TITLE
Publishing to Open VSX for use in VSCodium

### ISSUE THREAD

**Issue by fgimian** [go-task/vscode-task#26]
Hi there, thanks so much for this awesome project! 😄 

Would you please consider publishing your VS Code extension at https://open-vsx.org/  This is a fully open VS Code extension marketplace which is used by VSCodium.

Please see more information about publishing on Open VSX [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

Thanks heaps
Fotis

**Comment by andreynering** [comment]
I agree to do this, if easy enough. We may need some time to do all the setup, though.

/cc @pd93

**Comment by andreynering** [comment]
I just created a namespace on OpenVSX and it's currently pending verification: https://github.com/EclipseFdn/open-vsx.org/issues/1783

**Comment by pd93** [comment]
@fgimian @andreynering v0.1.0 and v0.1.1 are now available on the [Open VSX Registry](https://open-vsx.org/extension/task/vscode-task). I've created #46 to auto publish releases in the future.

**Comment by andreynering** [comment]
Awesome, thanks @pd93!

**Comment by fgimian** [comment]
> @fgimian @andreynering v0.1.0 and v0.1.1 are now available on the [Open VSX Registry](https://open-vsx.org/extension/task/vscode-task). I've created #46 to auto publish releases in the future.

Thank you so much for this, I can confirm that it is installable via VSCodium too! 🎉
